server:
  port: '${SERVER_PORT:8082}'

spring:
  data:
    mongodb:
      uri: 'mongodb://${MONGODB_USER:mediscreen}:${MONGODB_PASSWORD:mediscreen-pwd}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:mediscreen}?authSource=admin'
